### ISSUE TITLE
walk_bot: Cannot locate rosdep definition for [sole_poses_ims]

### ISSUE THREAD

**Issue by antbono** [ijnek/walk#45]
I am using ros2 rolling on ubuntu 22.04.

When I try to run rosdep on the walk repository i got this error

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
walk_bot: Cannot locate rosdep definition for [sole_poses_ims]
```

Do you have the same problem?

**Comment by ijnek** [comment]
Hmm, yes. Please consider putting a PR up to update the dependencies.repos file to include [sole_poses_ims](https://github.com/ijnek/sole_poses_ims)

**Comment by antbono** [comment]
Very strangely, I still have the same issue... 

The dependencies.repos file is the following now

```
repositories:
  biped_interfaces:
    type: git
    url: https://github.com/ros-sports/biped_interfaces.git
    version: rolling
  sole_poses_ims:
    type: git
    url: https://github.com/ijnek/sole_poses_ims.git
    version: rolling
```

I use the --recursive option when cloning the repository, but when using `rosdep install --from-paths src -i -r -y`, I get 

```
rosdep detected OS: [pop] aliasing it to: [ubuntu]
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
walk_bot: Cannot locate rosdep definition for [sole_poses_ims]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

```
because, actually, there is no sole_pose_ims package downloaded
